name: Code Test

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Set up node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test
